// <auto-generated>
//   由 UI 绑定工具生成，请不要手改 —— 重新生成会把改动覆盖掉。
//   重新生成：菜单 Tools/UI/绑定/生成全部面板的绑定代码（或选中预制体单独生成）
//   源预制体：Assets/Prefabs/LoadingPanel.prefab
// </auto-generated>

using UnityEngine;
using UnityEngine.UI;

public partial class LoadingPanel
{
    /// <summary>节点：Bg</summary>
    public Image bg;
    /// <summary>节点：ProgressSlider</summary>
    public Slider progressSlider;
    /// <summary>节点：ProgressSlider/Background</summary>
    public Image background;
    /// <summary>节点：ProgressSlider/Fill Area/Fill</summary>
    public Image fill;
    /// <summary>节点：TipText</summary>
    public Text tipText;
    /// <summary>节点：ProgressText</summary>
    public Text progressText;

    /// <summary>由生成代码统一赋值，时机在 OnInit 之前。</summary>
    protected override void BindNodes()
    {
        bg = Get<Image>("Bg");
        progressSlider = Get<Slider>("ProgressSlider");
        background = Get<Image>("Background");
        fill = Get<Image>("Fill");
        tipText = Get<Text>("TipText");
        progressText = Get<Text>("ProgressText");
    }
}
