// <auto-generated>
//   由 UI 绑定工具生成，请不要手改 —— 重新生成会把改动覆盖掉。
//   重新生成：菜单 Tools/UI/绑定/生成全部面板的绑定代码（或选中预制体单独生成）
//   源预制体：Assets/Prefabs/LoginPanel.prefab
// </auto-generated>

using UnityEngine;
using UnityEngine.UI;

public partial class LoginPanel
{
    /// <summary>节点：Bg</summary>
    public Image bg;
    /// <summary>节点：LoginButton</summary>
    public Button loginButton;
    /// <summary>节点：LoginButton/LoginText</summary>
    public Text loginText;
    /// <summary>节点：LoginTitle</summary>
    public Text loginTitle;
    /// <summary>节点：LoginTitle/AccountInput</summary>
    public InputField accountInput;
    /// <summary>节点：LoginTitle/AccountInput/LoginTitleText</summary>
    public Text loginTitleText;
    /// <summary>节点：PasswordTitle</summary>
    public Text passwordTitle;
    /// <summary>节点：PasswordTitle/PasswordInput</summary>
    public InputField passwordInput;
    /// <summary>节点：PasswordTitle/PasswordInput/PasswordTitleText</summary>
    public Text passwordTitleText;
    /// <summary>节点：RegisterButton</summary>
    public Button registerButton;
    /// <summary>节点：RegisterButton/RegisterText</summary>
    public Text registerText;
    /// <summary>节点：LanguageToggle</summary>
    public Button languageToggle;
    /// <summary>节点：LanguageToggle/Text</summary>
    public Text text;
    /// <summary>节点：ServerSelectButton</summary>
    public Button serverSelectButton;
    /// <summary>节点：ServerSelectButton/ServerSelectText</summary>
    public Text serverSelectText;

    /// <summary>由生成代码统一赋值，时机在 OnInit 之前。</summary>
    protected override void BindNodes()
    {
        bg = Get<Image>("Bg");
        loginButton = Get<Button>("LoginButton");
        loginText = Get<Text>("LoginText");
        loginTitle = Get<Text>("LoginTitle");
        accountInput = Get<InputField>("AccountInput");
        loginTitleText = Get<Text>("LoginTitleText");
        passwordTitle = Get<Text>("PasswordTitle");
        passwordInput = Get<InputField>("PasswordInput");
        passwordTitleText = Get<Text>("PasswordTitleText");
        registerButton = Get<Button>("RegisterButton");
        registerText = Get<Text>("RegisterText");
        languageToggle = Get<Button>("LanguageToggle");
        text = Get<Text>("Text");
        serverSelectButton = Get<Button>("ServerSelectButton");
        serverSelectText = Get<Text>("ServerSelectText");
    }
}
