// <auto-generated>
//   由 UI 绑定工具生成，请不要手改 —— 重新生成会把改动覆盖掉。
//   重新生成：菜单 Tools/UI/绑定/生成全部面板的绑定代码（或选中预制体单独生成）
//   源预制体：Assets/Prefabs/MainPanel.prefab
// </auto-generated>

using UnityEngine;
using UnityEngine.UI;

public partial class MainPanel
{
    /// <summary>节点：Background</summary>
    public Image background;
    /// <summary>节点：TitleText</summary>
    public Text titleText;
    /// <summary>节点：AccountText</summary>
    public Text accountText;
    /// <summary>节点：LevelText</summary>
    public Text levelText;
    /// <summary>节点：GoldText</summary>
    public Text goldText;
    /// <summary>节点：BagText</summary>
    public Text bagText;
    /// <summary>节点：PushText</summary>
    public Text pushText;
    /// <summary>节点：TipText</summary>
    public Text tipText;

    /// <summary>由生成代码统一赋值，时机在 OnInit 之前。</summary>
    protected override void BindNodes()
    {
        background = Get<Image>("Background");
        titleText = Get<Text>("TitleText");
        accountText = Get<Text>("AccountText");
        levelText = Get<Text>("LevelText");
        goldText = Get<Text>("GoldText");
        bagText = Get<Text>("BagText");
        pushText = Get<Text>("PushText");
        tipText = Get<Text>("TipText");
    }
}
