// <auto-generated>
//   由 UI 绑定工具生成，请不要手改 —— 重新生成会把改动覆盖掉。
//   重新生成：菜单 Tools/UI/绑定/生成全部面板的绑定代码（或选中预制体单独生成）
//   源预制体：Assets/Prefabs/SelectServerPanel.prefab
// </auto-generated>

using UnityEngine;
using UnityEngine.UI;

public partial class SelectServerPanel
{
    /// <summary>节点：Bg</summary>
    public Image bg;
    /// <summary>节点：Panel</summary>
    public Image panel;
    /// <summary>节点：Panel/Title</summary>
    public Text title;
    /// <summary>节点：Panel/CloseButton</summary>
    public Button closeButton;
    /// <summary>节点：Panel/CloseButton/Text</summary>
    public Text text;
    /// <summary>节点：Panel/Content/ServerItem</summary>
    public Button serverItem;
    /// <summary>节点：Panel/Content/ServerItem/Name</summary>
    public Text nameText;
    /// <summary>节点：Panel/Content/ServerItem/Status</summary>
    public Text status;

    /// <summary>由生成代码统一赋值，时机在 OnInit 之前。</summary>
    protected override void BindNodes()
    {
        bg = Get<Image>("Bg");
        panel = Get<Image>("Panel");
        title = Get<Text>("Title");
        closeButton = Get<Button>("CloseButton");
        text = Get<Text>("Text");
        serverItem = Get<Button>("ServerItem");
        nameText = Get<Text>("Name");
        status = Get<Text>("Status");
    }
}
